name: Android CI & Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Build (CI)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug (APK) + run unit tests
        run: ./gradlew testDebug assembleDebug

      - name: Upload debug APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/build/outputs/apk/debug/*.apk

  release:
    name: Sign & Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode keystore
        run: echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
        shell: bash
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: Build release (APK + AAB)
        run: ./gradlew clean assembleRelease bundleRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Sign release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/build/outputs
          signingKey: keystore.jks
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Collect artifacts
        run: |
          mkdir -p dist
          cp android/build/outputs/apk/release/*-signed.apk dist/ || true
          cp android/build/outputs/bundle/release/*-signed.aab dist/ || true
          cp android/build/outputs/apk/release/*.apk dist/ || true
          cp android/build/outputs/bundle/release/*.aab dist/ || true

      - name: Upload build artifacts (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}